export {
  defineCapabilities,
  jwksFromServiceBinding,
  jwksFromUrl,
  type JwksFromServiceBindingOptions,
  type JwksFromUrlOptions,
  type RemoteJwksFetch,
} from './capabilities.js';
export {
  bindCapabilityIdentity,
  capabilityIdentity,
  declaredScopes,
  defineService,
  requireScopes,
  RpcSession,
  RpcTarget,
  scope,
  serveCapabilityRpc,
  serviceDiscoveryDocument,
  verifyAuthenticationToken,
  type CapabilityFactory,
  type CapabilityRpcHandler,
  type DefineServiceInput,
  type DefineServiceOptions,
  type NormalizedCapability,
  type RpcSessionOptions,
  type RpcTransport,
  type ServeCapabilityRpcOptions,
  type ServiceCapabilityDefinition,
  type ServiceDefinition,
} from './discovery.js';
export {
  capabilityRpcSession,
  capabilityTokenCacheKey,
  createCapabilityTokenProvider,
  tokenExpiresAt,
  type AuthenticatedRoot,
  type CapabilityRpcSessionOptions,
  type CapabilityRpcTransport,
  type CreateCapabilityTokenProviderOptions,
} from './client.js';
export { verifyCapabilityToken } from '../shared/capability-tokens.js';
export {
  DEFAULT_CAPABILITY_TOKEN_TTL_SECONDS,
  DEFAULT_CAPABILITY_JWKS_CACHE_TTL_SECONDS,
  SERVICE_DISCOVERY_PATH,
  SERVICE_PLANE_AUTHORIZATION_SCHEME,
  SERVICE_PLANE_CAPABILITY_JWKS_PATH,
  SERVICE_PLANE_CAPABILITY_TOKEN_PATH,
} from '../shared/types.js';
export type {
  CapabilityCatalog,
  CapabilityIdentity,
  CapabilityJwks,
  CapabilityJwksResolver,
  CapabilityScopeDefinition,
  CapabilityTokenCache,
  CapabilityTokenCacheEntry,
  CapabilityTokenProvider,
  CapabilityVerifierOptions,
  FetchLike,
  IssueCapabilityTokenInput,
  IssuedCapabilityToken,
  ServiceCapabilityDescriptor,
  ServiceCapabilityVisibility,
  ServiceDiscoveryDocument,
  ServiceRpcTransport,
} from '../shared/types.js';
